// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped;

public class PrettyPrinter
{
  //For certain applications increasing the initial size of the buffer may improve performance.
  private static final int INITIAL_BUFFER_SIZE = 128;
  private static final int INDENT_WIDTH = 2;
  //You may wish to change the parentheses used in precedence.
  private static final String _L_PAREN = new String("(");
  private static final String _R_PAREN = new String(")");
  //You may wish to change render
  private static void render(String s)
  {
    if (s.equals("{"))
    {
       onEmptyLine();
       buf_.append(s);
       _n_ = _n_ + INDENT_WIDTH;
       buf_.append("\n");
       indent();
    }
    else if (s.equals("(") || s.equals("["))
       buf_.append(s);
    else if (s.equals(")") || s.equals("]"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals("}"))
    {
       _n_ = _n_ - INDENT_WIDTH;
       onEmptyLine();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals(","))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals(";"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals("")) return;
    else if (s.trim().equals(""))
    {
       backup();
       buf_.append(s);
    }
    else
    {
       buf_.append(s);
       buf_.append(" ");
    }
  }


  //  print and show methods are defined for each category.
  public static String print(hardtyped.Absyn.Program foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(hardtyped.Absyn.Program foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(hardtyped.Absyn.ListExpr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(hardtyped.Absyn.ListExpr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(hardtyped.Absyn.Expr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(hardtyped.Absyn.Expr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  /***   You shouldn't need to change anything beyond this point.   ***/

  private static void pp(hardtyped.Absyn.Program foo, int _i_)
  {
    if (foo instanceof hardtyped.Absyn.ProgramExprs)
    {
       hardtyped.Absyn.ProgramExprs _programexprs = (hardtyped.Absyn.ProgramExprs) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_programexprs.listexpr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(hardtyped.Absyn.ListExpr foo, int _i_)
  {
    ppListExpr(foo.iterator(), _i_);
  }

  private static void ppListExpr(java.util.Iterator<hardtyped.Absyn.Expr> it, int _i_)
  {
    if (it.hasNext())
    {
      hardtyped.Absyn.Expr el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(";"); ppListExpr(it, _i_);
      }
    }
  }


  private static void pp(hardtyped.Absyn.Expr foo, int _i_)
  {
    if (foo instanceof hardtyped.Absyn.ConstTrue)
    {
       hardtyped.Absyn.ConstTrue _consttrue = (hardtyped.Absyn.ConstTrue) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("true");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof hardtyped.Absyn.ConstFalse)
    {
       hardtyped.Absyn.ConstFalse _constfalse = (hardtyped.Absyn.ConstFalse) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("false");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof hardtyped.Absyn.If)
    {
       hardtyped.Absyn.If _if = (hardtyped.Absyn.If) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("if");
       pp(_if.expr_1, 0);
       render("then");
       pp(_if.expr_2, 0);
       render("else");
       pp(_if.expr_3, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof hardtyped.Absyn.ConstZero)
    {
       hardtyped.Absyn.ConstZero _constzero = (hardtyped.Absyn.ConstZero) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("0");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof hardtyped.Absyn.Succ)
    {
       hardtyped.Absyn.Succ _succ = (hardtyped.Absyn.Succ) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("succ");
       pp(_succ.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof hardtyped.Absyn.Pred)
    {
       hardtyped.Absyn.Pred _pred = (hardtyped.Absyn.Pred) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("pred");
       pp(_pred.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof hardtyped.Absyn.IsZero)
    {
       hardtyped.Absyn.IsZero _iszero = (hardtyped.Absyn.IsZero) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("iszero");
       pp(_iszero.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof hardtyped.Absyn.Var)
    {
       hardtyped.Absyn.Var _var = (hardtyped.Absyn.Var) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_var.ident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof hardtyped.Absyn.Abstraction)
    {
       hardtyped.Absyn.Abstraction _abstraction = (hardtyped.Absyn.Abstraction) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("fun");
       render("(");
       pp(_abstraction.ident_, 0);
       render(")");
       render("{");
       render("return");
       pp(_abstraction.expr_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof hardtyped.Absyn.Application)
    {
       hardtyped.Absyn.Application _application = (hardtyped.Absyn.Application) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_application.expr_1, 0);
       pp(_application.expr_2, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }


  private static void sh(hardtyped.Absyn.Program foo)
  {
    if (foo instanceof hardtyped.Absyn.ProgramExprs)
    {
       hardtyped.Absyn.ProgramExprs _programexprs = (hardtyped.Absyn.ProgramExprs) foo;
       render("(");
       render("ProgramExprs");
       render("[");
       sh(_programexprs.listexpr_);
       render("]");
       render(")");
    }
  }

  private static void sh(hardtyped.Absyn.ListExpr foo)
  {
     for (java.util.Iterator<hardtyped.Absyn.Expr> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(hardtyped.Absyn.Expr foo)
  {
    if (foo instanceof hardtyped.Absyn.ConstTrue)
    {
       hardtyped.Absyn.ConstTrue _consttrue = (hardtyped.Absyn.ConstTrue) foo;
       render("ConstTrue");
    }
    if (foo instanceof hardtyped.Absyn.ConstFalse)
    {
       hardtyped.Absyn.ConstFalse _constfalse = (hardtyped.Absyn.ConstFalse) foo;
       render("ConstFalse");
    }
    if (foo instanceof hardtyped.Absyn.If)
    {
       hardtyped.Absyn.If _if = (hardtyped.Absyn.If) foo;
       render("(");
       render("If");
       sh(_if.expr_1);
       sh(_if.expr_2);
       sh(_if.expr_3);
       render(")");
    }
    if (foo instanceof hardtyped.Absyn.ConstZero)
    {
       hardtyped.Absyn.ConstZero _constzero = (hardtyped.Absyn.ConstZero) foo;
       render("ConstZero");
    }
    if (foo instanceof hardtyped.Absyn.Succ)
    {
       hardtyped.Absyn.Succ _succ = (hardtyped.Absyn.Succ) foo;
       render("(");
       render("Succ");
       sh(_succ.expr_);
       render(")");
    }
    if (foo instanceof hardtyped.Absyn.Pred)
    {
       hardtyped.Absyn.Pred _pred = (hardtyped.Absyn.Pred) foo;
       render("(");
       render("Pred");
       sh(_pred.expr_);
       render(")");
    }
    if (foo instanceof hardtyped.Absyn.IsZero)
    {
       hardtyped.Absyn.IsZero _iszero = (hardtyped.Absyn.IsZero) foo;
       render("(");
       render("IsZero");
       sh(_iszero.expr_);
       render(")");
    }
    if (foo instanceof hardtyped.Absyn.Var)
    {
       hardtyped.Absyn.Var _var = (hardtyped.Absyn.Var) foo;
       render("(");
       render("Var");
       sh(_var.ident_);
       render(")");
    }
    if (foo instanceof hardtyped.Absyn.Abstraction)
    {
       hardtyped.Absyn.Abstraction _abstraction = (hardtyped.Absyn.Abstraction) foo;
       render("(");
       render("Abstraction");
       sh(_abstraction.ident_);
       sh(_abstraction.expr_);
       render(")");
    }
    if (foo instanceof hardtyped.Absyn.Application)
    {
       hardtyped.Absyn.Application _application = (hardtyped.Absyn.Application) foo;
       render("(");
       render("Application");
       sh(_application.expr_1);
       sh(_application.expr_2);
       render(")");
    }
  }


  private static void pp(Integer n, int _i_) { buf_.append(n); buf_.append(" "); }
  private static void pp(Double d, int _i_) { buf_.append(String.format(java.util.Locale.ROOT, "%.15g ", d)); }
  private static void pp(String s, int _i_) { buf_.append(s); buf_.append(" "); }
  private static void pp(Character c, int _i_) { buf_.append("'" + c.toString() + "'"); buf_.append(" "); }
  private static void sh(Integer n) { render(n.toString()); }
  private static void sh(Double d) { render(String.format(java.util.Locale.ROOT, "%.15g", d)); }
  private static void sh(Character c) { render("'" + c.toString() + "'"); }
  private static void sh(String s) { printQuoted(s); }

  private static void printQuoted(String s) { render("\"" + s + "\""); }

  private static void indent()
  {
    int n = _n_;
    while (n > 0)
    {
      buf_.append(' ');
      n--;
    }
  }

  private static void backup()
  {
    int prev = buf_.length() - 1;
    if (prev >= 0 && buf_.charAt(prev) == ' ')
      buf_.setLength(prev);
  }

  private static void trim()
  {
    // Trim initial spaces
    int end = 0;
    int len = buf_.length();
    while (end < len && buf_.charAt(end) == ' ')
      end++;
    buf_.delete(0, end);
    // Trim trailing spaces
    removeTrailingSpaces();
  }

  private static void removeTrailingSpaces()
  {
    int end = buf_.length();
    while (end > 0 && buf_.charAt(end-1) == ' ')
      end--;
    buf_.setLength(end);
  }

  private static void removeTrailingWhitespace()
  {
    int end = buf_.length();
    while (end > 0 && (buf_.charAt(end-1) == ' ' || buf_.charAt(end-1) == '\n'))
      end--;
    buf_.setLength(end);
  }

  private static void onEmptyLine()
  {
    removeTrailingSpaces();
    int len = buf_.length();
    if (len > 0 && buf_.charAt(len-1) != '\n') buf_.append("\n");
    indent();
  }

  private static int _n_ = 0;
  private static StringBuilder buf_ = new StringBuilder(INITIAL_BUFFER_SIZE);
}

