// -*- Java -*- File generated by the BNF Converter (bnfc 2.9.4).
// Lexer definition for use with JLex
package hardtyped;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  final int unknown = -1;
  ComplexSymbolFactory.Location left = new ComplexSymbolFactory.Location(unknown, unknown);
  ComplexSymbolFactory cf = new ComplexSymbolFactory();
  public SymbolFactory getSymbolFactory() { return cf; }
  int yyline = unknown - 1;
  int yycolumn = unknown - 1;
  int yychar = unknown;
  public int line_num() { return (yyline+1); }
  public ComplexSymbolFactory.Location left_loc() {
    return left;
  }
  public ComplexSymbolFactory.Location right_loc() {
    ComplexSymbolFactory.Location left = left_loc();
  return left;
  }
  public String buff() {return new String(yy_buffer,yy_buffer_index,10).trim();}
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		57,
		59,
		59,
		59,
		59,
		59
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NO_ANCHOR,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NOT_ACCEPT,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NO_ANCHOR,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NO_ANCHOR,
		/* 49 */ YY_NOT_ACCEPT,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NOT_ACCEPT,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NOT_ACCEPT,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NOT_ACCEPT,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NOT_ACCEPT,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NOT_ACCEPT,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NO_ANCHOR,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NO_ANCHOR,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NO_ANCHOR,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NO_ANCHOR,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NO_ANCHOR,
		/* 71 */ YY_NO_ANCHOR,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NO_ANCHOR,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NO_ANCHOR,
		/* 76 */ YY_NO_ANCHOR,
		/* 77 */ YY_NO_ANCHOR,
		/* 78 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"32:9,40,33,32,40,31,32:18,40,32,35,32:4,39,32:2,15,14,32,1,11,9,34:10,3,32," +
"13,4,12,32:2,37,16,37:6,22,37:8,24,25,37,27,37:5,7,10,8,32,39,32,20,38,30,3" +
"8,19,36,38:2,28,38:2,18,38,21,17,38:2,26,29,23,38:6,5,2,6,32:66,37:23,32,37" +
":7,38:24,32,38:8,32:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,79,
"0,1,2,3,1:6,4,1:2,5,6,1:2,7,1,8,1:4,9,1:4,10:2,1,11,10:3,12,10:4,1:3,13,14," +
"15,16,17,14,18,19,20,21,22,16,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37," +
"38,39,40,41,42,43,10:2")[0];

	private int yy_nxt[][] = unpackFromString(44,41,
"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,78,64,78,46,65,66,78,72,67,78,73," +
"50,78:2,18,11,18,19,45,78:3,11,18,-1:43,20,-1:9,21,-1:31,22,-1:41,23,-1:4,2" +
"4,25,-1:4,26,-1:29,27,-1:40,28,-1:52,78,76,77:4,78,77,78:2,77,78,77:3,-1:3," +
"78,-1,77,78,77,78,-1:12,44,-1:22,19,-1:7,24:32,-1,24:7,-1:16,78,77:5,78,77," +
"78:2,77,78,77:3,-1:3,78,-1,77,78,77,78,-1:17,78,77:5,78,77,78:2,70,78,77:3," +
"-1:3,78,-1,77,78,77,78,-1:20,53,-1:14,36,-1:40,36,-1:7,49:9,51,49:24,31,49:" +
"5,-1:16,78,77:5,78,77,78:2,77,78,77,29,77,-1:3,78,-1,77,78,77,78,-1:35,47,-" +
"1:15,43,-1:47,78,77:4,30,78,77,78:2,77,78,77:3,-1:3,78,-1,77,78,77,78,-1:11" +
",49,-1:10,49,-1,49,-1:2,49,-1:8,49:2,-1:20,78,77:5,78,32,78:2,77,78,77:3,-1" +
":3,78,-1,77,78,77,78,-1:2,55,-1:32,47,-1:22,78,77:5,78,33,78:2,77,78,77:3,-" +
"1:3,78,-1,77,78,77,78,-1:17,78,77:5,78,34,78:2,77,78,77:3,-1:3,78,-1,77,78," +
"77,78,-1,1,41:14,48,41:15,-1,41,42,41:7,-1:16,78,77:5,78,77,78:2,35,78,77:3" +
",-1:3,78,-1,77,78,77,78,-1,1,11:30,-1,11,-1,11:7,-1:16,78,77,37,77:3,78,77," +
"78:2,77,78,77:3,-1:3,78,-1,77,78,77,78,-1:17,78,77:5,78,38,78:2,77,78,77:3," +
"-1:3,78,-1,77,78,77,78,-1:17,78,77:5,78,77,78:2,77,78,77:2,39,-1:3,78,-1,77" +
",78,77,78,-1:17,78,77:4,40,78,77,78:2,77,78,77:3,-1:3,78,-1,77,78,77,78,-1:" +
"17,78,77:2,52,77:2,78,77,78:2,77,78,77:3,-1:3,78,-1,77,78,77,78,-1:17,78,54" +
",77:4,78,77,78:2,77,78,77:3,-1:3,78,-1,77,78,77,78,-1:17,78,77:4,56,78,77,7" +
"8:2,77,78,77:3,-1:3,78,-1,77,78,77,78,-1:17,78,77:5,78,58,78:2,77,78,77:3,-" +
"1:3,78,-1,77,78,77,78,-1:17,78,77:3,60,77,78,77,78:2,77,78,77:3,-1:3,78,-1," +
"77,78,77,78,-1:17,78,77:5,78,77,78:2,77,78,61,77:2,-1:3,78,-1,77,78,77,78,-" +
"1:17,78,77:2,62,77:2,78,77,78:2,77,78,77:3,-1:3,78,-1,77,78,77,78,-1:17,78," +
"77:3,63,77,78,77,78:2,77,78,77:3,-1:3,78,-1,77,78,77,78,-1:17,78,77:2,68,77" +
":2,78,77,78:2,77,78,77:3,-1:3,78,-1,77,78,77,78,-1:17,78,77:4,69,78,77,78:2" +
",77,78,77:3,-1:3,78,-1,77,78,77,78,-1:17,78,77:2,71,77:2,78,77,78:2,77,78,7" +
"7:3,-1:3,78,-1,77,78,77,78,-1:17,78,77,74,77:3,78,77,78:2,77,78,77:3,-1:3,7" +
"8,-1,77,78,77,78,-1:17,78,75,77:4,78,77,78:2,77,78,77:3,-1:3,78,-1,77,78,77" +
",78,-1");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {

  return cf.newSymbol("EOF", sym.EOF, left_loc(), left_loc());
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return cf.newSymbol("", sym._SYMB_18, left_loc(), right_loc()); }
					case -3:
						break;
					case 3:
						{ return cf.newSymbol("", sym._SYMB_1, left_loc(), right_loc()); }
					case -4:
						break;
					case 4:
						{ return cf.newSymbol("", sym._SYMB_2, left_loc(), right_loc()); }
					case -5:
						break;
					case 5:
						{ return cf.newSymbol("", sym._SYMB_4, left_loc(), right_loc()); }
					case -6:
						break;
					case 6:
						{ return cf.newSymbol("", sym._SYMB_5, left_loc(), right_loc()); }
					case -7:
						break;
					case 7:
						{ return cf.newSymbol("", sym._SYMB_6, left_loc(), right_loc()); }
					case -8:
						break;
					case 8:
						{ return cf.newSymbol("", sym._SYMB_7, left_loc(), right_loc()); }
					case -9:
						break;
					case 9:
						{ return cf.newSymbol("", sym._SYMB_8, left_loc(), right_loc()); }
					case -10:
						break;
					case 10:
						{ return cf.newSymbol("", sym._SYMB_20, left_loc(), right_loc()); }
					case -11:
						break;
					case 11:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -12:
						break;
					case 12:
						{ return cf.newSymbol("", sym._SYMB_10, left_loc(), right_loc()); }
					case -13:
						break;
					case 13:
						{ return cf.newSymbol("", sym._SYMB_14, left_loc(), right_loc()); }
					case -14:
						break;
					case 14:
						{ return cf.newSymbol("", sym._SYMB_12, left_loc(), right_loc()); }
					case -15:
						break;
					case 15:
						{ return cf.newSymbol("", sym._SYMB_17, left_loc(), right_loc()); }
					case -16:
						break;
					case 16:
						{ return cf.newSymbol("", sym._SYMB_19, left_loc(), right_loc()); }
					case -17:
						break;
					case 17:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -18:
						break;
					case 18:
						{ /* ignore white space. */ }
					case -19:
						break;
					case 19:
						{ return cf.newSymbol("", sym.Int, left_loc(), right_loc(), yytext().intern()); }
					case -20:
						break;
					case 20:
						{ return cf.newSymbol("", sym._SYMB_0, left_loc(), right_loc()); }
					case -21:
						break;
					case 21:
						{ return cf.newSymbol("", sym._SYMB_11, left_loc(), right_loc()); }
					case -22:
						break;
					case 22:
						{ return cf.newSymbol("", sym._SYMB_3, left_loc(), right_loc()); }
					case -23:
						break;
					case 23:
						{ return cf.newSymbol("", sym._SYMB_16, left_loc(), right_loc()); }
					case -24:
						break;
					case 24:
						{ /* skip */ }
					case -25:
						break;
					case 25:
						{ return cf.newSymbol("", sym._SYMB_9, left_loc(), right_loc()); }
					case -26:
						break;
					case 26:
						{ yybegin(COMMENT); }
					case -27:
						break;
					case 27:
						{ return cf.newSymbol("", sym._SYMB_15, left_loc(), right_loc()); }
					case -28:
						break;
					case 28:
						{ return cf.newSymbol("", sym._SYMB_13, left_loc(), right_loc()); }
					case -29:
						break;
					case 29:
						{ return cf.newSymbol("", sym._SYMB_26, left_loc(), right_loc()); }
					case -30:
						break;
					case 30:
						{ return cf.newSymbol("", sym._SYMB_27, left_loc(), right_loc()); }
					case -31:
						break;
					case 31:
						{ return cf.newSymbol("", sym.Str, left_loc(), right_loc(), yytext().intern()); }
					case -32:
						break;
					case 32:
						{ return cf.newSymbol("", sym._SYMB_28, left_loc(), right_loc()); }
					case -33:
						break;
					case 33:
						{ return cf.newSymbol("", sym._SYMB_30, left_loc(), right_loc()); }
					case -34:
						break;
					case 34:
						{ return cf.newSymbol("", sym._SYMB_22, left_loc(), right_loc()); }
					case -35:
						break;
					case 35:
						{ return cf.newSymbol("", sym._SYMB_24, left_loc(), right_loc()); }
					case -36:
						break;
					case 36:
						{ return cf.newSymbol("", sym.Real, left_loc(), right_loc(), yytext().intern()); }
					case -37:
						break;
					case 37:
						{ return cf.newSymbol("", sym._SYMB_23, left_loc(), right_loc()); }
					case -38:
						break;
					case 38:
						{ return cf.newSymbol("", sym._SYMB_25, left_loc(), right_loc()); }
					case -39:
						break;
					case 39:
						{ return cf.newSymbol("", sym._SYMB_29, left_loc(), right_loc()); }
					case -40:
						break;
					case 40:
						{ return cf.newSymbol("", sym._SYMB_21, left_loc(), right_loc()); }
					case -41:
						break;
					case 41:
						{ /* skip */ }
					case -42:
						break;
					case 42:
						{ /* skip */ }
					case -43:
						break;
					case 43:
						{ yybegin(YYINITIAL); }
					case -44:
						break;
					case 45:
						{ throw new Error("Illegal Character <"+yytext()+">"); }
					case -45:
						break;
					case 46:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -46:
						break;
					case 47:
						{ return cf.newSymbol("", sym.Real, left_loc(), right_loc(), yytext().intern()); }
					case -47:
						break;
					case 48:
						{ /* skip */ }
					case -48:
						break;
					case 50:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -49:
						break;
					case 52:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -50:
						break;
					case 54:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -51:
						break;
					case 56:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -52:
						break;
					case 58:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -53:
						break;
					case 60:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -54:
						break;
					case 61:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -55:
						break;
					case 62:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -56:
						break;
					case 63:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -57:
						break;
					case 64:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -58:
						break;
					case 65:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -59:
						break;
					case 66:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -60:
						break;
					case 67:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -61:
						break;
					case 68:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -62:
						break;
					case 69:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -63:
						break;
					case 70:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -64:
						break;
					case 71:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -65:
						break;
					case 72:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -66:
						break;
					case 73:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -67:
						break;
					case 74:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -68:
						break;
					case 75:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -69:
						break;
					case 76:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -70:
						break;
					case 77:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -71:
						break;
					case 78:
						{ return cf.newSymbol("", sym.Unit, left_loc(), right_loc(), yytext().intern()); }
					case -72:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
