// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class FunctionBody1  extends FunctionBody {
  public final Body body_;
  public FunctionBody1(Body p1) { body_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.FunctionBody.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.FunctionBody1) {
      hardtyped.Absyn.FunctionBody1 x = (hardtyped.Absyn.FunctionBody1)o;
      return this.body_.equals(x.body_);
    }
    return false;
  }

  public int hashCode() {
    return this.body_.hashCode();
  }


}
