// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class If  extends Stm {
  public final IfStart ifstart_;
  public final Else else_;
  public If(IfStart p1, Else p2) { ifstart_ = p1; else_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.If) {
      hardtyped.Absyn.If x = (hardtyped.Absyn.If)o;
      return this.ifstart_.equals(x.ifstart_) && this.else_.equals(x.else_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ifstart_.hashCode())+this.else_.hashCode();
  }


}
