// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class ImportPlain  extends Stm {
  public final Identifier identifier_;
  public ImportPlain(Identifier p1) { identifier_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.ImportPlain) {
      hardtyped.Absyn.ImportPlain x = (hardtyped.Absyn.ImportPlain)o;
      return this.identifier_.equals(x.identifier_);
    }
    return false;
  }

  public int hashCode() {
    return this.identifier_.hashCode();
  }


}
