// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Letrec  extends Stm {
  public final Identifier identifier_;
  public final Type type_;
  public Letrec(Identifier p1, Type p2) { identifier_ = p1; type_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Letrec) {
      hardtyped.Absyn.Letrec x = (hardtyped.Absyn.Letrec)o;
      return this.identifier_.equals(x.identifier_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.identifier_.hashCode())+this.type_.hashCode();
  }


}
