// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Relation1  extends Relation {
  public final Factor factor_;
  public Relation1(Factor p1) { factor_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Relation.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Relation1) {
      hardtyped.Absyn.Relation1 x = (hardtyped.Absyn.Relation1)o;
      return this.factor_.equals(x.factor_);
    }
    return false;
  }

  public int hashCode() {
    return this.factor_.hashCode();
  }


}
