// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped;

/** Abstract Visitor */

public class AbstractVisitor<R,A> implements AllVisitor<R,A> {
    /* Program */
    public R visit(hardtyped.Absyn.ProgramExprs p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(hardtyped.Absyn.Program p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* Expr */
    public R visit(hardtyped.Absyn.ConstTrue p, A arg) { return visitDefault(p, arg); }
    public R visit(hardtyped.Absyn.ConstFalse p, A arg) { return visitDefault(p, arg); }
    public R visit(hardtyped.Absyn.If p, A arg) { return visitDefault(p, arg); }
    public R visit(hardtyped.Absyn.ConstZero p, A arg) { return visitDefault(p, arg); }
    public R visit(hardtyped.Absyn.Succ p, A arg) { return visitDefault(p, arg); }
    public R visit(hardtyped.Absyn.Pred p, A arg) { return visitDefault(p, arg); }
    public R visit(hardtyped.Absyn.IsZero p, A arg) { return visitDefault(p, arg); }
    public R visit(hardtyped.Absyn.Var p, A arg) { return visitDefault(p, arg); }
    public R visit(hardtyped.Absyn.Abstraction p, A arg) { return visitDefault(p, arg); }
    public R visit(hardtyped.Absyn.Application p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(hardtyped.Absyn.Expr p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }

}
