// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped;

/** All Visitor */

public interface AllVisitor<R,A> extends
  hardtyped.Absyn.Program.Visitor<R,A>,
  hardtyped.Absyn.Expr.Visitor<R,A>
{}
