// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped;
/** Composition Visitor
*/

public class ComposVisitor<A> implements
  hardtyped.Absyn.Program.Visitor<hardtyped.Absyn.Program,A>,
  hardtyped.Absyn.Expr.Visitor<hardtyped.Absyn.Expr,A>
{
    /* Program */
    public hardtyped.Absyn.Program visit(hardtyped.Absyn.ProgramExprs p, A arg)
    {
      hardtyped.Absyn.ListExpr listexpr_ = new hardtyped.Absyn.ListExpr();
      for (hardtyped.Absyn.Expr x : p.listexpr_)
      {
        listexpr_.add(x.accept(this,arg));
      }
      return new hardtyped.Absyn.ProgramExprs(listexpr_);
    }

    /* Expr */
    public hardtyped.Absyn.Expr visit(hardtyped.Absyn.ConstTrue p, A arg)
    {
      return new hardtyped.Absyn.ConstTrue();
    }
    public hardtyped.Absyn.Expr visit(hardtyped.Absyn.ConstFalse p, A arg)
    {
      return new hardtyped.Absyn.ConstFalse();
    }
    public hardtyped.Absyn.Expr visit(hardtyped.Absyn.If p, A arg)
    {
      hardtyped.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      hardtyped.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      hardtyped.Absyn.Expr expr_3 = p.expr_3.accept(this, arg);
      return new hardtyped.Absyn.If(expr_1, expr_2, expr_3);
    }
    public hardtyped.Absyn.Expr visit(hardtyped.Absyn.ConstZero p, A arg)
    {
      return new hardtyped.Absyn.ConstZero();
    }
    public hardtyped.Absyn.Expr visit(hardtyped.Absyn.Succ p, A arg)
    {
      hardtyped.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new hardtyped.Absyn.Succ(expr_);
    }
    public hardtyped.Absyn.Expr visit(hardtyped.Absyn.Pred p, A arg)
    {
      hardtyped.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new hardtyped.Absyn.Pred(expr_);
    }
    public hardtyped.Absyn.Expr visit(hardtyped.Absyn.IsZero p, A arg)
    {
      hardtyped.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new hardtyped.Absyn.IsZero(expr_);
    }
    public hardtyped.Absyn.Expr visit(hardtyped.Absyn.Var p, A arg)
    {
      String ident_ = p.ident_;
      return new hardtyped.Absyn.Var(ident_);
    }
    public hardtyped.Absyn.Expr visit(hardtyped.Absyn.Abstraction p, A arg)
    {
      String ident_ = p.ident_;
      hardtyped.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new hardtyped.Absyn.Abstraction(ident_, expr_);
    }
    public hardtyped.Absyn.Expr visit(hardtyped.Absyn.Application p, A arg)
    {
      hardtyped.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      hardtyped.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new hardtyped.Absyn.Application(expr_1, expr_2);
    }
}
