// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Application  extends Expr {
  public final Expr expr_;
  public final ListExprSequence listexprsequence_;
  public Application(Expr p1, ListExprSequence p2) { expr_ = p1; listexprsequence_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Application) {
      hardtyped.Absyn.Application x = (hardtyped.Absyn.Application)o;
      return this.expr_.equals(x.expr_) && this.listexprsequence_.equals(x.listexprsequence_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.listexprsequence_.hashCode();
  }


}
