// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Conjunction1  extends Conjunction {
  public final Relation relation_1, relation_2;
  public Conjunction1(Relation p1, Relation p2) { relation_1 = p1; relation_2 = p2; }

  public <R,A> R accept(hardtyped.Absyn.Conjunction.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Conjunction1) {
      hardtyped.Absyn.Conjunction1 x = (hardtyped.Absyn.Conjunction1)o;
      return this.relation_1.equals(x.relation_1) && this.relation_2.equals(x.relation_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.relation_1.hashCode())+this.relation_2.hashCode();
  }


}
