// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class EmptyPrintFunction  extends Expr {
  public final String print_;
  public EmptyPrintFunction(String p1) { print_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.EmptyPrintFunction) {
      hardtyped.Absyn.EmptyPrintFunction x = (hardtyped.Absyn.EmptyPrintFunction)o;
      return this.print_.equals(x.print_);
    }
    return false;
  }

  public int hashCode() {
    return this.print_.hashCode();
  }


}
