// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Exprs  extends Expr {
  public final ListExpr listexpr_;
  public int line_num, col_num, offset;
  public Exprs(ListExpr p1) { listexpr_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Exprs) {
      hardtyped.Absyn.Exprs x = (hardtyped.Absyn.Exprs)o;
      return this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.listexpr_.hashCode();
  }


}
