// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class Expr implements java.io.Serializable {
  public abstract <R,A> R accept(Expr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.If p, A arg);
    public R visit(hardtyped.Absyn.Let1 p, A arg);
    public R visit(hardtyped.Absyn.Let2 p, A arg);
    public R visit(hardtyped.Absyn.Disjunction p, A arg);
    public R visit(hardtyped.Absyn.Conjunction p, A arg);
    public R visit(hardtyped.Absyn.Relation p, A arg);
    public R visit(hardtyped.Absyn.Factor p, A arg);
    public R visit(hardtyped.Absyn.Term p, A arg);
    public R visit(hardtyped.Absyn.Unary p, A arg);
    public R visit(hardtyped.Absyn.Function p, A arg);

  }

}
