// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Expression2  extends Expression {
  public final Conjunction conjunction_;
  public Expression2(Conjunction p1) { conjunction_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Expression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Expression2) {
      hardtyped.Absyn.Expression2 x = (hardtyped.Absyn.Expression2)o;
      return this.conjunction_.equals(x.conjunction_);
    }
    return false;
  }

  public int hashCode() {
    return this.conjunction_.hashCode();
  }


}
