// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Factor2  extends Factor {
  public final Term term_1, term_2;
  public final PlusMinus plusminus_;
  public Factor2(Term p1, PlusMinus p2, Term p3) { term_1 = p1; plusminus_ = p2; term_2 = p3; }

  public <R,A> R accept(hardtyped.Absyn.Factor.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Factor2) {
      hardtyped.Absyn.Factor2 x = (hardtyped.Absyn.Factor2)o;
      return this.term_1.equals(x.term_1) && this.plusminus_.equals(x.plusminus_) && this.term_2.equals(x.term_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.term_1.hashCode())+this.plusminus_.hashCode())+this.term_2.hashCode();
  }


}
