// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class FinalInnerExpression  extends InnerExpr {
  public final InnerExpr innerexpr_;
  public FinalInnerExpression(InnerExpr p1) { innerexpr_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.InnerExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.FinalInnerExpression) {
      hardtyped.Absyn.FinalInnerExpression x = (hardtyped.Absyn.FinalInnerExpression)o;
      return this.innerexpr_.equals(x.innerexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.innerexpr_.hashCode();
  }


}
