// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class FuncBody implements java.io.Serializable {
  public abstract <R,A> R accept(FuncBody.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.FuncBody1 p, A arg);

  }

}
