// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Function  extends Expr {
  public final ListFuncArg listfuncarg_;
  public final ListExpr listexpr_;
  public int line_num, col_num, offset;
  public Function(ListFuncArg p1, ListExpr p2) { listfuncarg_ = p1; listexpr_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Function) {
      hardtyped.Absyn.Function x = (hardtyped.Absyn.Function)o;
      return this.listfuncarg_.equals(x.listfuncarg_) && this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listfuncarg_.hashCode())+this.listexpr_.hashCode();
  }


}
