// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Function  extends Expr {
  public final FuncArg funcarg_;
  public final InExpr inexpr_;
  public Function(FuncArg p1, InExpr p2) { funcarg_ = p1; inexpr_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Function) {
      hardtyped.Absyn.Function x = (hardtyped.Absyn.Function)o;
      return this.funcarg_.equals(x.funcarg_) && this.inexpr_.equals(x.inexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.funcarg_.hashCode())+this.inexpr_.hashCode();
  }


}
