// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class FuncBody1  extends FuncBody {
  public final ListExpr listexpr_;
  public FuncBody1(ListExpr p1) { listexpr_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.FuncBody.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.FuncBody1) {
      hardtyped.Absyn.FuncBody1 x = (hardtyped.Absyn.FuncBody1)o;
      return this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.listexpr_.hashCode();
  }


}
