// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class FunctionWithReturnType  extends Expr {
  public final ListFuncArg listfuncarg_;
  public final ListExpr listexpr_;
  public final Type type_;
  public int line_num, col_num, offset;
  public FunctionWithReturnType(ListFuncArg p1, ListExpr p2, Type p3) { listfuncarg_ = p1; listexpr_ = p2; type_ = p3; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.FunctionWithReturnType) {
      hardtyped.Absyn.FunctionWithReturnType x = (hardtyped.Absyn.FunctionWithReturnType)o;
      return this.listfuncarg_.equals(x.listfuncarg_) && this.listexpr_.equals(x.listexpr_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.listfuncarg_.hashCode())+this.listexpr_.hashCode())+this.type_.hashCode();
  }


}
