// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Identifier1  extends Identifier {
  public final String str_;
  public Identifier1(String p1) { str_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Identifier.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Identifier1) {
      hardtyped.Absyn.Identifier1 x = (hardtyped.Absyn.Identifier1)o;
      return this.str_.equals(x.str_);
    }
    return false;
  }

  public int hashCode() {
    return this.str_.hashCode();
  }


}
