// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class IfMultiple  extends IfExpr {
  public final Expr expr_;
  public final ListExpr listexpr_;
  public IfMultiple(Expr p1, ListExpr p2) { expr_ = p1; listexpr_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.IfExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.IfMultiple) {
      hardtyped.Absyn.IfMultiple x = (hardtyped.Absyn.IfMultiple)o;
      return this.expr_.equals(x.expr_) && this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.listexpr_.hashCode();
  }


}
