// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class IfStart1  extends IfStart {
  public final Expression expression_;
  public final Body body_;
  public IfStart1(Expression p1, Body p2) { expression_ = p1; body_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.IfStart.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.IfStart1) {
      hardtyped.Absyn.IfStart1 x = (hardtyped.Absyn.IfStart1)o;
      return this.expression_.equals(x.expression_) && this.body_.equals(x.body_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expression_.hashCode())+this.body_.hashCode();
  }


}
