// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class IfStmt  extends Expr {
  public final IfExpr ifexpr_;
  public IfStmt(IfExpr p1) { ifexpr_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.IfStmt) {
      hardtyped.Absyn.IfStmt x = (hardtyped.Absyn.IfStmt)o;
      return this.ifexpr_.equals(x.ifexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.ifexpr_.hashCode();
  }


}
