// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class ImportFile  extends ImportFileName {
  public final String ident_, packageextension_;
  public ImportFile(String p1, String p2) { ident_ = p1; packageextension_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.ImportFileName.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.ImportFile) {
      hardtyped.Absyn.ImportFile x = (hardtyped.Absyn.ImportFile)o;
      return this.ident_.equals(x.ident_) && this.packageextension_.equals(x.packageextension_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.packageextension_.hashCode();
  }


}
