// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class ImportPath  extends ModuleIdentifier {
  public final ListPath listpath_;
  public final ImportFileName importfilename_;
  public ImportPath(ListPath p1, ImportFileName p2) { listpath_ = p1; importfilename_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.ModuleIdentifier.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.ImportPath) {
      hardtyped.Absyn.ImportPath x = (hardtyped.Absyn.ImportPath)o;
      return this.listpath_.equals(x.listpath_) && this.importfilename_.equals(x.importfilename_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listpath_.hashCode())+this.importfilename_.hashCode();
  }


}
