// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Import1  extends Expr {
  public final String string_;
  public int line_num, col_num, offset;
  public Import1(String p1) { string_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Import1) {
      hardtyped.Absyn.Import1 x = (hardtyped.Absyn.Import1)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
