// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class ImportAs  extends Stm {
  public final Identifier identifier_1, identifier_2;
  public ImportAs(Identifier p1, Identifier p2) { identifier_1 = p1; identifier_2 = p2; }

  public <R,A> R accept(hardtyped.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.ImportAs) {
      hardtyped.Absyn.ImportAs x = (hardtyped.Absyn.ImportAs)o;
      return this.identifier_1.equals(x.identifier_1) && this.identifier_2.equals(x.identifier_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.identifier_1.hashCode())+this.identifier_2.hashCode();
  }


}
