// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class InExpr implements java.io.Serializable {
  public abstract <R,A> R accept(InExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.MultipleExpressions p, A arg);
    public R visit(hardtyped.Absyn.FinalExpression p, A arg);
    public R visit(hardtyped.Absyn.InnerExpression p, A arg);

  }

}
