// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class InnerExpression  extends InExpr {
  public final Expr expr_;
  public InnerExpression(Expr p1) { expr_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.InExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.InnerExpression) {
      hardtyped.Absyn.InnerExpression x = (hardtyped.Absyn.InnerExpression)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
