// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class InnerExpr implements java.io.Serializable {
  public abstract <R,A> R accept(InnerExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.BaseInnerExpression p, A arg);
    public R visit(hardtyped.Absyn.MultipleInnerExpression p, A arg);
    public R visit(hardtyped.Absyn.FinalInnerExpression p, A arg);

  }

}
