// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class IntegerLiteral  extends Literal {
  public final Integer integer_;
  public IntegerLiteral(Integer p1) { integer_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Literal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.IntegerLiteral) {
      hardtyped.Absyn.IntegerLiteral x = (hardtyped.Absyn.IntegerLiteral)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
