// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Let1  extends Expr {
  public final LetHead lethead_;
  public Let1(LetHead p1) { lethead_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Let1) {
      hardtyped.Absyn.Let1 x = (hardtyped.Absyn.Let1)o;
      return this.lethead_.equals(x.lethead_);
    }
    return false;
  }

  public int hashCode() {
    return this.lethead_.hashCode();
  }


}
