// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class LetType  extends Expr {
  public final VarDec vardec_;
  public final Type type_;
  public int line_num, col_num, offset;
  public LetType(VarDec p1, Type p2) { vardec_ = p1; type_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.LetType) {
      hardtyped.Absyn.LetType x = (hardtyped.Absyn.LetType)o;
      return this.vardec_.equals(x.vardec_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.vardec_.hashCode())+this.type_.hashCode();
  }


}
