// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class Literal implements java.io.Serializable {
  public abstract <R,A> R accept(Literal.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.ArrayLiteral p, A arg);
    public R visit(hardtyped.Absyn.FunctionLiteral p, A arg);
    public R visit(hardtyped.Absyn.RecordLiteral p, A arg);

  }

}
