// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class MultipleExpressions  extends InExpr {
  public final InExpr inexpr_1, inexpr_2;
  public MultipleExpressions(InExpr p1, InExpr p2) { inexpr_1 = p1; inexpr_2 = p2; }

  public <R,A> R accept(hardtyped.Absyn.InExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.MultipleExpressions) {
      hardtyped.Absyn.MultipleExpressions x = (hardtyped.Absyn.MultipleExpressions)o;
      return this.inexpr_1.equals(x.inexpr_1) && this.inexpr_2.equals(x.inexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.inexpr_1.hashCode())+this.inexpr_2.hashCode();
  }


}
