// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class MultipleVars  extends VarDec {
  public final VarDec vardec_1, vardec_2;
  public MultipleVars(VarDec p1, VarDec p2) { vardec_1 = p1; vardec_2 = p2; }

  public <R,A> R accept(hardtyped.Absyn.VarDec.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.MultipleVars) {
      hardtyped.Absyn.MultipleVars x = (hardtyped.Absyn.MultipleVars)o;
      return this.vardec_1.equals(x.vardec_1) && this.vardec_2.equals(x.vardec_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.vardec_1.hashCode())+this.vardec_2.hashCode();
  }


}
