// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class MultipleRecordValue  extends Record {
  public final Record record_1, record_2;
  public MultipleRecordValue(Record p1, Record p2) { record_1 = p1; record_2 = p2; }

  public <R,A> R accept(hardtyped.Absyn.Record.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.MultipleRecordValue) {
      hardtyped.Absyn.MultipleRecordValue x = (hardtyped.Absyn.MultipleRecordValue)o;
      return this.record_1.equals(x.record_1) && this.record_2.equals(x.record_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.record_1.hashCode())+this.record_2.hashCode();
  }


}
