// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class MultipleArgs  extends FuncArg {
  public final VarDec vardec_;
  public final FuncArg funcarg_;
  public MultipleArgs(VarDec p1, FuncArg p2) { vardec_ = p1; funcarg_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.FuncArg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.MultipleArgs) {
      hardtyped.Absyn.MultipleArgs x = (hardtyped.Absyn.MultipleArgs)o;
      return this.vardec_.equals(x.vardec_) && this.funcarg_.equals(x.funcarg_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.vardec_.hashCode())+this.funcarg_.hashCode();
  }


}
