// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class MultipleInnerExpression  extends InnerExpr {
  public final InnerExpr innerexpr_1, innerexpr_2;
  public MultipleInnerExpression(InnerExpr p1, InnerExpr p2) { innerexpr_1 = p1; innerexpr_2 = p2; }

  public <R,A> R accept(hardtyped.Absyn.InnerExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.MultipleInnerExpression) {
      hardtyped.Absyn.MultipleInnerExpression x = (hardtyped.Absyn.MultipleInnerExpression)o;
      return this.innerexpr_1.equals(x.innerexpr_1) && this.innerexpr_2.equals(x.innerexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.innerexpr_1.hashCode())+this.innerexpr_2.hashCode();
  }


}
