// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class MultipleVarsFinal  extends VarDec {
  public final VarDec vardec_;
  public MultipleVarsFinal(VarDec p1) { vardec_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.VarDec.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.MultipleVarsFinal) {
      hardtyped.Absyn.MultipleVarsFinal x = (hardtyped.Absyn.MultipleVarsFinal)o;
      return this.vardec_.equals(x.vardec_);
    }
    return false;
  }

  public int hashCode() {
    return this.vardec_.hashCode();
  }


}
