// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class Op implements java.io.Serializable {
  public abstract <R,A> R accept(Op.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.Op1 p, A arg);
    public R visit(hardtyped.Absyn.Op2 p, A arg);
    public R visit(hardtyped.Absyn.Op3 p, A arg);
    public R visit(hardtyped.Absyn.Op4 p, A arg);
    public R visit(hardtyped.Absyn.Op5 p, A arg);
    public R visit(hardtyped.Absyn.Op6 p, A arg);

  }

}
