// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class PlusMinus implements java.io.Serializable {
  public abstract <R,A> R accept(PlusMinus.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.Plus p, A arg);
    public R visit(hardtyped.Absyn.Minus p, A arg);

  }

}
