// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Progr  extends Program {
  public final Stm stm_;
  public Progr(Stm p1) { stm_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Progr) {
      hardtyped.Absyn.Progr x = (hardtyped.Absyn.Progr)o;
      return this.stm_.equals(x.stm_);
    }
    return false;
  }

  public int hashCode() {
    return this.stm_.hashCode();
  }


}
