// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class ReadRealFunction  extends Expr {
  public final String readreal_;
  public final ListExprSequence listexprsequence_;
  public int line_num, col_num, offset;
  public ReadRealFunction(String p1, ListExprSequence p2) { readreal_ = p1; listexprsequence_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.ReadRealFunction) {
      hardtyped.Absyn.ReadRealFunction x = (hardtyped.Absyn.ReadRealFunction)o;
      return this.readreal_.equals(x.readreal_) && this.listexprsequence_.equals(x.listexprsequence_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.readreal_.hashCode())+this.listexprsequence_.hashCode();
  }


}
