// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class ReadFunction  extends Expr {
  public final String read_;
  public final Expr expr_;
  public ReadFunction(String p1, Expr p2) { read_ = p1; expr_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.ReadFunction) {
      hardtyped.Absyn.ReadFunction x = (hardtyped.Absyn.ReadFunction)o;
      return this.read_.equals(x.read_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.read_.hashCode())+this.expr_.hashCode();
  }


}
