// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class ReadStringFunction  extends Expr {
  public final String readstring_;
  public final ListExprSequence listexprsequence_;
  public int line_num, col_num, offset;
  public ReadStringFunction(String p1, ListExprSequence p2) { readstring_ = p1; listexprsequence_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.ReadStringFunction) {
      hardtyped.Absyn.ReadStringFunction x = (hardtyped.Absyn.ReadStringFunction)o;
      return this.readstring_.equals(x.readstring_) && this.listexprsequence_.equals(x.listexprsequence_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.readstring_.hashCode())+this.listexprsequence_.hashCode();
  }


}
