// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class ReadBoolFunction  extends Expr {
  public final String readbool_;
  public final ListExprSequence listexprsequence_;
  public ReadBoolFunction(String p1, ListExprSequence p2) { readbool_ = p1; listexprsequence_ = p2; }

  public <R,A> R accept(hardtyped.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.ReadBoolFunction) {
      hardtyped.Absyn.ReadBoolFunction x = (hardtyped.Absyn.ReadBoolFunction)o;
      return this.readbool_.equals(x.readbool_) && this.listexprsequence_.equals(x.listexprsequence_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.readbool_.hashCode())+this.listexprsequence_.hashCode();
  }


}
