// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class Record implements java.io.Serializable {
  public abstract <R,A> R accept(Record.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.BaseRecordNameValue p, A arg);
    public R visit(hardtyped.Absyn.BaseRecordName p, A arg);

  }

}
