// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class RecordType  extends Type {
  public final ListRecordElemType listrecordelemtype_;
  public int line_num, col_num, offset;
  public RecordType(ListRecordElemType p1) { listrecordelemtype_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.RecordType) {
      hardtyped.Absyn.RecordType x = (hardtyped.Absyn.RecordType)o;
      return this.listrecordelemtype_.equals(x.listrecordelemtype_);
    }
    return false;
  }

  public int hashCode() {
    return this.listrecordelemtype_.hashCode();
  }


}
