// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class RecordLiteral  extends Literal {
  public final RecordElement recordelement_;
  public RecordLiteral(RecordElement p1) { recordelement_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Literal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.RecordLiteral) {
      hardtyped.Absyn.RecordLiteral x = (hardtyped.Absyn.RecordLiteral)o;
      return this.recordelement_.equals(x.recordelement_);
    }
    return false;
  }

  public int hashCode() {
    return this.recordelement_.hashCode();
  }


}
