// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Relation2  extends Relation {
  public final Factor factor_1, factor_2;
  public final Operand operand_;
  public Relation2(Factor p1, Operand p2, Factor p3) { factor_1 = p1; operand_ = p2; factor_2 = p3; }

  public <R,A> R accept(hardtyped.Absyn.Relation.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Relation2) {
      hardtyped.Absyn.Relation2 x = (hardtyped.Absyn.Relation2)o;
      return this.factor_1.equals(x.factor_1) && this.operand_.equals(x.operand_) && this.factor_2.equals(x.factor_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.factor_1.hashCode())+this.operand_.hashCode())+this.factor_2.hashCode();
  }


}
