// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class Stm implements java.io.Serializable {
  public abstract <R,A> R accept(Stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.ImportAs p, A arg);
    public R visit(hardtyped.Absyn.ImportPlain p, A arg);
    public R visit(hardtyped.Absyn.If p, A arg);
    public R visit(hardtyped.Absyn.Let p, A arg);
    public R visit(hardtyped.Absyn.Letrec p, A arg);

  }

}
