// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class StringLiteral  extends Literal {
  public final String string_;
  public StringLiteral(String p1) { string_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Literal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.StringLiteral) {
      hardtyped.Absyn.StringLiteral x = (hardtyped.Absyn.StringLiteral)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
