// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class StringType  extends Type {
  public int line_num, col_num, offset;
  public StringType() { }

  public <R,A> R accept(hardtyped.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.StringType) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
