// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Term1  extends Term {
  public final Unary unary_;
  public Term1(Unary p1) { unary_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Term1) {
      hardtyped.Absyn.Term1 x = (hardtyped.Absyn.Term1)o;
      return this.unary_.equals(x.unary_);
    }
    return false;
  }

  public int hashCode() {
    return this.unary_.hashCode();
  }


}
