// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Term2  extends Term {
  public final Unary unary_1, unary_2;
  public final MultDiv multdiv_;
  public Term2(Unary p1, MultDiv p2, Unary p3) { unary_1 = p1; multdiv_ = p2; unary_2 = p3; }

  public <R,A> R accept(hardtyped.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Term2) {
      hardtyped.Absyn.Term2 x = (hardtyped.Absyn.Term2)o;
      return this.unary_1.equals(x.unary_1) && this.multdiv_.equals(x.multdiv_) && this.unary_2.equals(x.unary_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.unary_1.hashCode())+this.multdiv_.hashCode())+this.unary_2.hashCode();
  }


}
