// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.IntType p, A arg);
    public R visit(hardtyped.Absyn.RealType p, A arg);
    public R visit(hardtyped.Absyn.BoolType p, A arg);
    public R visit(hardtyped.Absyn.StringType p, A arg);
    public R visit(hardtyped.Absyn.UnitType p, A arg);

  }

}
