// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class UnaryDefLiteral  extends UnaryDef {
  public final Literal literal_;
  public UnaryDefLiteral(Literal p1) { literal_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.UnaryDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.UnaryDefLiteral) {
      hardtyped.Absyn.UnaryDefLiteral x = (hardtyped.Absyn.UnaryDefLiteral)o;
      return this.literal_.equals(x.literal_);
    }
    return false;
  }

  public int hashCode() {
    return this.literal_.hashCode();
  }


}
