// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class UnaryDef implements java.io.Serializable {
  public abstract <R,A> R accept(UnaryDef.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.UnaryDefLiteral p, A arg);
    public R visit(hardtyped.Absyn.UnaryDefIdent p, A arg);

  }

}
