// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class Unary implements java.io.Serializable {
  public abstract <R,A> R accept(Unary.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.Unary1 p, A arg);
    public R visit(hardtyped.Absyn.Unary2 p, A arg);
    public R visit(hardtyped.Absyn.Unary3 p, A arg);

  }

}
