// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Unary1  extends Unary {
  public final Expression expression_;
  public Unary1(Expression p1) { expression_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.Unary.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Unary1) {
      hardtyped.Absyn.Unary1 x = (hardtyped.Absyn.Unary1)o;
      return this.expression_.equals(x.expression_);
    }
    return false;
  }

  public int hashCode() {
    return this.expression_.hashCode();
  }


}
