// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class Unary3  extends Unary {
  public final UnaryPrefix unaryprefix_;
  public final Identifier identifier_;
  public final Ascription ascription_;
  public Unary3(UnaryPrefix p1, Identifier p2, Ascription p3) { unaryprefix_ = p1; identifier_ = p2; ascription_ = p3; }

  public <R,A> R accept(hardtyped.Absyn.Unary.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.Unary3) {
      hardtyped.Absyn.Unary3 x = (hardtyped.Absyn.Unary3)o;
      return this.unaryprefix_.equals(x.unaryprefix_) && this.identifier_.equals(x.identifier_) && this.ascription_.equals(x.ascription_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.unaryprefix_.hashCode())+this.identifier_.hashCode())+this.ascription_.hashCode();
  }


}
