// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class UnaryPrefix implements java.io.Serializable {
  public abstract <R,A> R accept(UnaryPrefix.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.PlusPfx p, A arg);
    public R visit(hardtyped.Absyn.MinusPfx p, A arg);
    public R visit(hardtyped.Absyn.NotPfx p, A arg);

  }

}
