// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public class UntypedVar  extends VarDec {
  public final String ident_;
  public UntypedVar(String p1) { ident_ = p1; }

  public <R,A> R accept(hardtyped.Absyn.VarDec.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof hardtyped.Absyn.UntypedVar) {
      hardtyped.Absyn.UntypedVar x = (hardtyped.Absyn.UntypedVar)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
