// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class Value implements java.io.Serializable {
  public abstract <R,A> R accept(Value.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.IntValue p, A arg);
    public R visit(hardtyped.Absyn.RealValue p, A arg);
    public R visit(hardtyped.Absyn.StringValue p, A arg);
    public R visit(hardtyped.Absyn.BoolValue p, A arg);
    public R visit(hardtyped.Absyn.UnitValue p, A arg);
    public R visit(hardtyped.Absyn.RecordConstr p, A arg);

  }

}
