// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class VarDec implements java.io.Serializable {
  public abstract <R,A> R accept(VarDec.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.TypedVar p, A arg);
    public R visit(hardtyped.Absyn.UntypedVar p, A arg);
    public R visit(hardtyped.Absyn.DotVar p, A arg);

  }

}
