// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class VarPath implements java.io.Serializable {
  public abstract <R,A> R accept(VarPath.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.Lib p, A arg);

  }

}
