// File generated by the BNF Converter (bnfc 2.9.4).

package hardtyped.Absyn;

public abstract class Expr implements java.io.Serializable {
  public abstract <R,A> R accept(Expr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(hardtyped.Absyn.ConstTrue p, A arg);
    public R visit(hardtyped.Absyn.ConstFalse p, A arg);
    public R visit(hardtyped.Absyn.If p, A arg);
    public R visit(hardtyped.Absyn.ConstZero p, A arg);
    public R visit(hardtyped.Absyn.Succ p, A arg);
    public R visit(hardtyped.Absyn.Pred p, A arg);
    public R visit(hardtyped.Absyn.IsZero p, A arg);
    public R visit(hardtyped.Absyn.Var p, A arg);
    public R visit(hardtyped.Absyn.Abstraction p, A arg);
    public R visit(hardtyped.Absyn.Application p, A arg);

  }

}
